# Generated by Django 3.2.11 on 2022-02-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('multi_headline_1', models.CharField(blank=True, max_length=50, null=True)),
                ('multi_headline_2', models.CharField(blank=True, max_length=50, null=True)),
                ('multi_headline_3', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.CharField(blank=True, max_length=50, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=50, null=True)),
                ('bio', models.CharField(blank=True, max_length=50, null=True)),
                ('spoken', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('interests', models.CharField(blank=True, max_length=50, null=True)),
                ('upload_cv', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d')),
            ],
        ),
    ]
