# Generated by Django 3.2.11 on 2022-02-18 21:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meerbalajcv', '0002_auto_20220218_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='DOB',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
