# Generated by Django 3.2.11 on 2022-02-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meerbalajcv', '0004_alter_profile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='DOB',
            field=models.DateTimeField(default=0),
        ),
    ]
