# Generated by Django 3.2.11 on 2022-02-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meerbalajcv', '0005_alter_profile_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.DateTimeField(default=0)),
                ('To', models.DateTimeField(default=0)),
                ('learning_place', models.CharField(max_length=50, null=True)),
                ('degree', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.DateTimeField(default=0)),
                ('To', models.DateTimeField(default=0)),
                ('company', models.CharField(max_length=50, null=True)),
                ('job_title', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
