# Generated by Django 3.2.11 on 2022-02-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meerbalajcv', '0006_education_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(default='Matriculation', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='learning_place',
            field=models.CharField(default='School', max_length=50, null=True),
        ),
    ]
