# Generated by Django 3.2.11 on 2022-02-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meerbalajcv', '0007_auto_20220218_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(default='Google', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='job_title',
            field=models.CharField(default='Odoo Developer', max_length=50, null=True),
        ),
    ]
