# Generated by Django 3.2.11 on 2022-02-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meerbalajcv', '0010_rename_skills_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bar_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_before_name', models.CharField(default='Completed Projects', max_length=50, null=True)),
                ('complete_before_count', models.IntegerField(default=1, null=True)),
            ],
        ),
    ]
