# Generated by Django 3.2.11 on 2022-02-18 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meerbalajcv', '0011_bar_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bar_Images',
            new_name='Bar_Image',
        ),
    ]
