# Generated by Django 3.2.11 on 2022-02-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meerbalajcv', '0017_alter_portfolio_image_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_from_name', models.CharField(max_length=50, null=True)),
                ('contact_from_email', models.CharField(max_length=50, null=True)),
                ('contact_message', models.CharField(max_length=50, null=True)),
                ('contact_us_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Line_Bar_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_img', models.CharField(max_length=50, null=True)),
                ('bar_img', models.ImageField(null=True, upload_to='images/%Y/%m/%d')),
            ],
        ),
        migrations.RenameField(
            model_name='categorie',
            old_name='name',
            new_name='name_category',
        ),
        migrations.RenameField(
            model_name='portfolio_image',
            old_name='name',
            new_name='name_project',
        ),
    ]
