# Generated by Django 3.2.11 on 2022-02-18 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meerbalajcv', '0018_auto_20220218_2158'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='Contact',
        ),
    ]
