# Generated by Django 3.2.11 on 2022-02-18 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meerbalajcv', '0019_rename_contactus_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_us_time',
            new_name='contact_us_date_time',
        ),
    ]
