# Generated by Django 3.2.11 on 2022-02-18 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meerbalajcv', '0020_rename_contact_us_time_contact_contact_us_date_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contact_U',
        ),
    ]
