# Generated by Django 3.2.11 on 2022-02-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meerbalajcv', '0021_rename_contact_contact_u'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_u',
            name='contact_us_date_time',
            field=models.DateTimeField(),
        ),
    ]
