# Generated by Django 3.2.11 on 2022-02-18 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meerbalajcv', '0022_alter_contact_u_contact_us_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_u',
            name='contact_us_date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
