# Generated by Django 3.2.11 on 2022-02-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meerbalajcv', '0023_alter_contact_u_contact_us_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
