# Generated by Django 3.2.11 on 2022-02-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meerbalajcv', '0024_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='From',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='education',
            name='To',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='experience',
            name='From',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='experience',
            name='To',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='DOB',
            field=models.DateField(default=0),
        ),
    ]
