# Generated by Django 3.2.11 on 2022-02-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meerbalajcv', '0025_auto_20220219_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='From',
            field=models.DateTimeField(default=0),
        ),
        migrations.AlterField(
            model_name='education',
            name='To',
            field=models.DateTimeField(default=0),
        ),
        migrations.AlterField(
            model_name='experience',
            name='From',
            field=models.DateTimeField(default=0),
        ),
        migrations.AlterField(
            model_name='experience',
            name='To',
            field=models.DateTimeField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='DOB',
            field=models.DateTimeField(default=0),
        ),
    ]
