# Generated by Django 3.2.11 on 2022-02-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meerbalajcv', '0029_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='From',
            field=models.DateTimeField(default=0),
        ),
        migrations.AlterField(
            model_name='education',
            name='To',
            field=models.DateTimeField(default=0),
        ),
        migrations.AlterField(
            model_name='experience',
            name='From',
            field=models.DateTimeField(default=0),
        ),
        migrations.AlterField(
            model_name='experience',
            name='To',
            field=models.DateTimeField(default=0),
        ),
    ]
