# Generated by Django 3.2.11 on 2022-02-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meerbalajcv', '0030_auto_20220219_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.CharField(blank=True, default='https://www.eusol.net/', max_length=50, null=True),
        ),
    ]
