# Generated by Django 3.2.11 on 2022-02-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meerbalajcv', '0032_auto_20220219_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='client_feedback',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
