# Generated by Django 3.2.11 on 2022-03-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meerbalajcv', '0034_auto_20220304_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar_image',
            name='mark',
            field=models.CharField(default='cell', max_length=50, null=True),
        ),
    ]
