# Generated by Django 3.2.11 on 2022-03-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meerbalajcv', '0035_alter_bar_image_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='check_remove_cv',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
